export const consultants = [
  {
    id: "1",
    name: "Alex Johnson",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "New York, NY",
    yearsOfExperience: 8,
    expertise: [
      "Project Management",
      "Digital Transformation",
      "Agile",
      "Strategy",
    ],
    bio: "Experienced project manager with a focus on digital transformation initiatives. Led multiple Fortune 500 companies through successful technology transitions.",
  },
  {
    id: "2",
    name: "Sarah Chen",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "San Francisco, CA",
    yearsOfExperience: 6,
    expertise: [
      "Data Science",
      "Machine Learning",
      "Python",
      "Business Intelligence",
    ],
    bio: "Data scientist with expertise in predictive analytics and machine learning. Helped companies leverage data to drive business decisions and optimize operations.",
  },
  {
    id: "3",
    name: "Michael Rodriguez",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "Chicago, IL",
    yearsOfExperience: 12,
    expertise: [
      "Change Management",
      "Leadership Development",
      "Organizational Design",
      "Executive Coaching",
    ],
    bio: "Organizational development consultant specializing in change management and leadership coaching. Worked with diverse industries to improve team performance and culture.",
  },
  {
    id: "4",
    name: "Priya Patel",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "Boston, MA",
    yearsOfExperience: 5,
    expertise: [
      "UX Research",
      "Product Strategy",
      "Design Thinking",
      "Customer Experience",
    ],
    bio: "Product strategist with a background in UX research and design thinking. Helps companies create user-centered products and services that drive engagement.",
  },
  {
    id: "5",
    name: "David Kim",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "Seattle, WA",
    yearsOfExperience: 9,
    expertise: ["Cloud Architecture", "DevOps", "AWS", "System Integration"],
    bio: "Cloud architect with extensive experience in AWS and DevOps practices. Specializes in helping organizations migrate to and optimize cloud infrastructure.",
  },
  {
    id: "6",
    name: "Emma Wilson",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "Austin, TX",
    yearsOfExperience: 7,
    expertise: [
      "Marketing Strategy",
      "Growth Hacking",
      "Digital Marketing",
      "Brand Development",
    ],
    bio: "Marketing strategist focused on growth and digital channels. Has helped startups and established companies alike develop and execute effective marketing campaigns.",
  },
  {
    id: "7",
    name: "James Thompson",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "Denver, CO",
    yearsOfExperience: 15,
    expertise: [
      "Financial Analysis",
      "M&A",
      "Investment Strategy",
      "Risk Management",
    ],
    bio: "Financial consultant with expertise in mergers and acquisitions, investment strategy, and risk management. Former investment banker with a track record of successful deals.",
  },
  {
    id: "8",
    name: "Olivia Martinez",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "Los Angeles, CA",
    yearsOfExperience: 4,
    expertise: [
      "Content Strategy",
      "Social Media",
      "Brand Storytelling",
      "Digital Content",
    ],
    bio: "Content strategist who helps brands tell compelling stories across digital channels. Specializes in creating engaging content that drives audience growth and engagement.",
  },
  {
    id: "9",
    name: "Robert Lee",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "Atlanta, GA",
    yearsOfExperience: 10,
    expertise: [
      "Supply Chain Optimization",
      "Logistics",
      "Operations Management",
      "Process Improvement",
    ],
    bio: "Operations consultant specializing in supply chain optimization and process improvement. Has helped companies reduce costs and improve efficiency across their operations.",
  },
  {
    id: "10",
    name: "Sophia Williams",
    avatar: "/placeholder.svg?height=100&width=100",
    location: "Miami, FL",
    yearsOfExperience: 6,
    expertise: [
      "HR Strategy",
      "Talent Acquisition",
      "Employee Experience",
      "Organizational Culture",
    ],
    bio: "HR consultant focused on talent acquisition and employee experience. Helps organizations build strong cultures and effective talent management strategies.",
  },
];
